// Code generated by lister-gen. DO NOT EDIT.

package v1

// DeepOneListerExpansion allows custom methods to be added to
// DeepOneLister.
type DeepOneListerExpansion interface{}

// DeepOneNamespaceListerExpansion allows custom methods to be added to
// DeepOneNamespaceLister.
type DeepOneNamespaceListerExpansion interface{}
