/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/apis/simple/v1/generated.proto

/*
	Package v1 is a generated protocol buffer package.

	It is generated from these files:
		github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/apis/simple/v1/generated.proto

	It has these top-level messages:
		DeepOne
		DeepOneList
		DeepOneSpec
		DeepOneStatus
		SampleElem
		SampleListElem
		SampleListPointerElem
		SampleListPointerSubElem
		SampleListSubElem
		SampleMapElem
		SampleMapPointerElem
		SampleMapPointerSubElem
		SampleMapSubElem
		SamplePointerElem
		SamplePointerSubElem
		SampleSubElem
*/
package v1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/apis/simple/common"

import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func (m *DeepOne) Reset()                    { *m = DeepOne{} }
func (*DeepOne) ProtoMessage()               {}
func (*DeepOne) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{0} }

func (m *DeepOneList) Reset()                    { *m = DeepOneList{} }
func (*DeepOneList) ProtoMessage()               {}
func (*DeepOneList) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{1} }

func (m *DeepOneSpec) Reset()                    { *m = DeepOneSpec{} }
func (*DeepOneSpec) ProtoMessage()               {}
func (*DeepOneSpec) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{2} }

func (m *DeepOneStatus) Reset()                    { *m = DeepOneStatus{} }
func (*DeepOneStatus) ProtoMessage()               {}
func (*DeepOneStatus) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{3} }

func (m *SampleElem) Reset()                    { *m = SampleElem{} }
func (*SampleElem) ProtoMessage()               {}
func (*SampleElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{4} }

func (m *SampleListElem) Reset()                    { *m = SampleListElem{} }
func (*SampleListElem) ProtoMessage()               {}
func (*SampleListElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{5} }

func (m *SampleListPointerElem) Reset()                    { *m = SampleListPointerElem{} }
func (*SampleListPointerElem) ProtoMessage()               {}
func (*SampleListPointerElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{6} }

func (m *SampleListPointerSubElem) Reset()      { *m = SampleListPointerSubElem{} }
func (*SampleListPointerSubElem) ProtoMessage() {}
func (*SampleListPointerSubElem) Descriptor() ([]byte, []int) {
	return fileDescriptorGenerated, []int{7}
}

func (m *SampleListSubElem) Reset()                    { *m = SampleListSubElem{} }
func (*SampleListSubElem) ProtoMessage()               {}
func (*SampleListSubElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{8} }

func (m *SampleMapElem) Reset()                    { *m = SampleMapElem{} }
func (*SampleMapElem) ProtoMessage()               {}
func (*SampleMapElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{9} }

func (m *SampleMapPointerElem) Reset()                    { *m = SampleMapPointerElem{} }
func (*SampleMapPointerElem) ProtoMessage()               {}
func (*SampleMapPointerElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{10} }

func (m *SampleMapPointerSubElem) Reset()      { *m = SampleMapPointerSubElem{} }
func (*SampleMapPointerSubElem) ProtoMessage() {}
func (*SampleMapPointerSubElem) Descriptor() ([]byte, []int) {
	return fileDescriptorGenerated, []int{11}
}

func (m *SampleMapSubElem) Reset()                    { *m = SampleMapSubElem{} }
func (*SampleMapSubElem) ProtoMessage()               {}
func (*SampleMapSubElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{12} }

func (m *SamplePointerElem) Reset()                    { *m = SamplePointerElem{} }
func (*SamplePointerElem) ProtoMessage()               {}
func (*SamplePointerElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{13} }

func (m *SamplePointerSubElem) Reset()                    { *m = SamplePointerSubElem{} }
func (*SamplePointerSubElem) ProtoMessage()               {}
func (*SamplePointerSubElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{14} }

func (m *SampleSubElem) Reset()                    { *m = SampleSubElem{} }
func (*SampleSubElem) ProtoMessage()               {}
func (*SampleSubElem) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{15} }

func init() {
	proto.RegisterType((*DeepOne)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.DeepOne")
	proto.RegisterType((*DeepOneList)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.DeepOneList")
	proto.RegisterType((*DeepOneSpec)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.DeepOneSpec")
	proto.RegisterType((*DeepOneStatus)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.DeepOneStatus")
	proto.RegisterType((*SampleElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleElem")
	proto.RegisterType((*SampleListElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleListElem")
	proto.RegisterType((*SampleListPointerElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleListPointerElem")
	proto.RegisterType((*SampleListPointerSubElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleListPointerSubElem")
	proto.RegisterType((*SampleListSubElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleListSubElem")
	proto.RegisterType((*SampleMapElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleMapElem")
	proto.RegisterType((*SampleMapPointerElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleMapPointerElem")
	proto.RegisterType((*SampleMapPointerSubElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleMapPointerSubElem")
	proto.RegisterType((*SampleMapSubElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleMapSubElem")
	proto.RegisterType((*SamplePointerElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SamplePointerElem")
	proto.RegisterType((*SamplePointerSubElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SamplePointerSubElem")
	proto.RegisterType((*SampleSubElem)(nil), "github.com.yue9944882.apiserver_builder_alpha_protobuf_example.pkg.apis.simple.v1.SampleSubElem")
}
func (m *DeepOne) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeepOne) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ObjectMeta.Size()))
	n1, err := m.ObjectMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Spec.Size()))
	n2, err := m.Spec.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x1a
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Status.Size()))
	n3, err := m.Status.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	return i, nil
}

func (m *DeepOneList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeepOneList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ListMeta.Size()))
	n4, err := m.ListMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	if len(m.Items) > 0 {
		for _, msg := range m.Items {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *DeepOneSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeepOneSpec) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.FishRequired))
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Sample.Size()))
	n5, err := m.Sample.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	if m.SamplePointer != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.SamplePointer.Size()))
		n6, err := m.SamplePointer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.SampleList) > 0 {
		for _, msg := range m.SampleList {
			dAtA[i] = 0x22
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.SamplePointerList) > 0 {
		for _, msg := range m.SamplePointerList {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.SampleMap) > 0 {
		keysForSampleMap := make([]string, 0, len(m.SampleMap))
		for k := range m.SampleMap {
			keysForSampleMap = append(keysForSampleMap, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForSampleMap)
		for _, k := range keysForSampleMap {
			dAtA[i] = 0x32
			i++
			v := m.SampleMap[string(k)]
			msgSize := 0
			if (&v) != nil {
				msgSize = (&v).Size()
				msgSize += 1 + sovGenerated(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovGenerated(uint64(len(k))) + msgSize
			i = encodeVarintGenerated(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64((&v).Size()))
			n7, err := (&v).MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n7
		}
	}
	dAtA[i] = 0x40
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.SamplePrimitiveAlias))
	dAtA[i] = 0x4a
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Const)))
	i += copy(dAtA[i:], m.Const)
	if m.ConstPtr != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.ConstPtr)))
		i += copy(dAtA[i:], *m.ConstPtr)
	}
	if len(m.ConstSlice) > 0 {
		for _, s := range m.ConstSlice {
			dAtA[i] = 0x5a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.ConstMap) > 0 {
		keysForConstMap := make([]string, 0, len(m.ConstMap))
		for k := range m.ConstMap {
			keysForConstMap = append(keysForConstMap, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForConstMap)
		for _, k := range keysForConstMap {
			dAtA[i] = 0x62
			i++
			v := m.ConstMap[string(k)]
			mapSize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			i = encodeVarintGenerated(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func (m *DeepOneStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeepOneStatus) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ActualFish))
	return i, nil
}

func (m *SampleElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Sub.Size()))
	n8, err := m.Sub.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	return i, nil
}

func (m *SampleListElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleListElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Sub) > 0 {
		for _, msg := range m.Sub {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *SampleListPointerElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleListPointerElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Sub) > 0 {
		for _, msg := range m.Sub {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *SampleListPointerSubElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleListPointerSubElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Foo)))
	i += copy(dAtA[i:], m.Foo)
	return i, nil
}

func (m *SampleListSubElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleListSubElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Foo)))
	i += copy(dAtA[i:], m.Foo)
	return i, nil
}

func (m *SampleMapElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleMapElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Sub) > 0 {
		keysForSub := make([]string, 0, len(m.Sub))
		for k := range m.Sub {
			keysForSub = append(keysForSub, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForSub)
		for _, k := range keysForSub {
			dAtA[i] = 0xa
			i++
			v := m.Sub[string(k)]
			msgSize := 0
			if (&v) != nil {
				msgSize = (&v).Size()
				msgSize += 1 + sovGenerated(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovGenerated(uint64(len(k))) + msgSize
			i = encodeVarintGenerated(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64((&v).Size()))
			n9, err := (&v).MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n9
		}
	}
	return i, nil
}

func (m *SampleMapPointerElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleMapPointerElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *SampleMapPointerSubElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleMapPointerSubElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Foo)))
	i += copy(dAtA[i:], m.Foo)
	return i, nil
}

func (m *SampleMapSubElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleMapSubElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Foo)))
	i += copy(dAtA[i:], m.Foo)
	return i, nil
}

func (m *SamplePointerElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SamplePointerElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Sub != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.Sub.Size()))
		n10, err := m.Sub.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	return i, nil
}

func (m *SamplePointerSubElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SamplePointerSubElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Foo)))
	i += copy(dAtA[i:], m.Foo)
	return i, nil
}

func (m *SampleSubElem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleSubElem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Foo)))
	i += copy(dAtA[i:], m.Foo)
	return i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *DeepOne) Size() (n int) {
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *DeepOneList) Size() (n int) {
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *DeepOneSpec) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.FishRequired))
	l = m.Sample.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if m.SamplePointer != nil {
		l = m.SamplePointer.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.SampleList) > 0 {
		for _, e := range m.SampleList {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.SamplePointerList) > 0 {
		for _, e := range m.SamplePointerList {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.SampleMap) > 0 {
		for k, v := range m.SampleMap {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + l + sovGenerated(uint64(l))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	n += 1 + sovGenerated(uint64(m.SamplePrimitiveAlias))
	l = len(m.Const)
	n += 1 + l + sovGenerated(uint64(l))
	if m.ConstPtr != nil {
		l = len(*m.ConstPtr)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.ConstSlice) > 0 {
		for _, s := range m.ConstSlice {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.ConstMap) > 0 {
		for k, v := range m.ConstMap {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *DeepOneStatus) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.ActualFish))
	return n
}

func (m *SampleElem) Size() (n int) {
	var l int
	_ = l
	l = m.Sub.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *SampleListElem) Size() (n int) {
	var l int
	_ = l
	if len(m.Sub) > 0 {
		for _, e := range m.Sub {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *SampleListPointerElem) Size() (n int) {
	var l int
	_ = l
	if len(m.Sub) > 0 {
		for _, e := range m.Sub {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *SampleListPointerSubElem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Foo)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *SampleListSubElem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Foo)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *SampleMapElem) Size() (n int) {
	var l int
	_ = l
	if len(m.Sub) > 0 {
		for k, v := range m.Sub {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + l + sovGenerated(uint64(l))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *SampleMapPointerElem) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *SampleMapPointerSubElem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Foo)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *SampleMapSubElem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Foo)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *SamplePointerElem) Size() (n int) {
	var l int
	_ = l
	if m.Sub != nil {
		l = m.Sub.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *SamplePointerSubElem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Foo)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *SampleSubElem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Foo)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DeepOne) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeepOne{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(this.ObjectMeta.String(), "ObjectMeta", "k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "DeepOneSpec", "DeepOneSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "DeepOneStatus", "DeepOneStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeepOneList) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeepOneList{`,
		`ListMeta:` + strings.Replace(strings.Replace(this.ListMeta.String(), "ListMeta", "k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Items), "DeepOne", "DeepOne", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeepOneSpec) String() string {
	if this == nil {
		return "nil"
	}
	keysForSampleMap := make([]string, 0, len(this.SampleMap))
	for k := range this.SampleMap {
		keysForSampleMap = append(keysForSampleMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForSampleMap)
	mapStringForSampleMap := "map[string]SampleMapElem{"
	for _, k := range keysForSampleMap {
		mapStringForSampleMap += fmt.Sprintf("%v: %v,", k, this.SampleMap[k])
	}
	mapStringForSampleMap += "}"
	keysForConstMap := make([]string, 0, len(this.ConstMap))
	for k := range this.ConstMap {
		keysForConstMap = append(keysForConstMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForConstMap)
	mapStringForConstMap := "map[string]github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType{"
	for _, k := range keysForConstMap {
		mapStringForConstMap += fmt.Sprintf("%v: %v,", k, this.ConstMap[k])
	}
	mapStringForConstMap += "}"
	s := strings.Join([]string{`&DeepOneSpec{`,
		`FishRequired:` + fmt.Sprintf("%v", this.FishRequired) + `,`,
		`Sample:` + strings.Replace(strings.Replace(this.Sample.String(), "SampleElem", "SampleElem", 1), `&`, ``, 1) + `,`,
		`SamplePointer:` + strings.Replace(fmt.Sprintf("%v", this.SamplePointer), "SamplePointerElem", "SamplePointerElem", 1) + `,`,
		`SampleList:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.SampleList), "SampleListElem", "SampleListElem", 1), `&`, ``, 1) + `,`,
		`SamplePointerList:` + strings.Replace(fmt.Sprintf("%v", this.SamplePointerList), "SampleListPointerElem", "SampleListPointerElem", 1) + `,`,
		`SampleMap:` + mapStringForSampleMap + `,`,
		`SamplePrimitiveAlias:` + fmt.Sprintf("%v", this.SamplePrimitiveAlias) + `,`,
		`Const:` + fmt.Sprintf("%v", this.Const) + `,`,
		`ConstPtr:` + valueToStringGenerated(this.ConstPtr) + `,`,
		`ConstSlice:` + fmt.Sprintf("%v", this.ConstSlice) + `,`,
		`ConstMap:` + mapStringForConstMap + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeepOneStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeepOneStatus{`,
		`ActualFish:` + fmt.Sprintf("%v", this.ActualFish) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleElem{`,
		`Sub:` + strings.Replace(strings.Replace(this.Sub.String(), "SampleSubElem", "SampleSubElem", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleListElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleListElem{`,
		`Sub:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Sub), "SampleListSubElem", "SampleListSubElem", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleListPointerElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleListPointerElem{`,
		`Sub:` + strings.Replace(fmt.Sprintf("%v", this.Sub), "SampleListPointerSubElem", "SampleListPointerSubElem", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleListPointerSubElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleListPointerSubElem{`,
		`Foo:` + fmt.Sprintf("%v", this.Foo) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleListSubElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleListSubElem{`,
		`Foo:` + fmt.Sprintf("%v", this.Foo) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleMapElem) String() string {
	if this == nil {
		return "nil"
	}
	keysForSub := make([]string, 0, len(this.Sub))
	for k := range this.Sub {
		keysForSub = append(keysForSub, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForSub)
	mapStringForSub := "map[string]SampleMapSubElem{"
	for _, k := range keysForSub {
		mapStringForSub += fmt.Sprintf("%v: %v,", k, this.Sub[k])
	}
	mapStringForSub += "}"
	s := strings.Join([]string{`&SampleMapElem{`,
		`Sub:` + mapStringForSub + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleMapPointerElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleMapPointerElem{`,
		`}`,
	}, "")
	return s
}
func (this *SampleMapPointerSubElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleMapPointerSubElem{`,
		`Foo:` + fmt.Sprintf("%v", this.Foo) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleMapSubElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleMapSubElem{`,
		`Foo:` + fmt.Sprintf("%v", this.Foo) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SamplePointerElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SamplePointerElem{`,
		`Sub:` + strings.Replace(fmt.Sprintf("%v", this.Sub), "SamplePointerSubElem", "SamplePointerSubElem", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SamplePointerSubElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SamplePointerSubElem{`,
		`Foo:` + fmt.Sprintf("%v", this.Foo) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleSubElem) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleSubElem{`,
		`Foo:` + fmt.Sprintf("%v", this.Foo) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DeepOne) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeepOne: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeepOne: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeepOneList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeepOneList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeepOneList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, DeepOne{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeepOneSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeepOneSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeepOneSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FishRequired", wireType)
			}
			m.FishRequired = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FishRequired |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sample", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sample.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SamplePointer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SamplePointer == nil {
				m.SamplePointer = &SamplePointerElem{}
			}
			if err := m.SamplePointer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SampleList = append(m.SampleList, SampleListElem{})
			if err := m.SampleList[len(m.SampleList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SamplePointerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SamplePointerList = append(m.SamplePointerList, &SampleListPointerElem{})
			if err := m.SamplePointerList[len(m.SamplePointerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SampleMap == nil {
				m.SampleMap = make(map[string]SampleMapElem)
			}
			var mapkey string
			mapvalue := &SampleMapElem{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthGenerated
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthGenerated
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &SampleMapElem{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.SampleMap[mapkey] = *mapvalue
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SamplePrimitiveAlias", wireType)
			}
			m.SamplePrimitiveAlias = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SamplePrimitiveAlias |= (SamplePrimitiveAlias(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Const", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Const = github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConstPtr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType(dAtA[iNdEx:postIndex])
			m.ConstPtr = &s
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConstSlice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConstSlice = append(m.ConstSlice, github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConstMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConstMap == nil {
				m.ConstMap = make(map[string]github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType)
			}
			var mapkey string
			var mapvalue github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ConstMap[mapkey] = ((github_com_yue9944882_apiserver_builder_alpha_protobuf_example_pkg_apis_simple_common.CustomType)(mapvalue))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeepOneStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeepOneStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeepOneStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualFish", wireType)
			}
			m.ActualFish = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActualFish |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sub", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sub.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleListElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleListElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleListElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sub", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sub = append(m.Sub, SampleListSubElem{})
			if err := m.Sub[len(m.Sub)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleListPointerElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleListPointerElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleListPointerElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sub", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sub = append(m.Sub, &SampleListPointerSubElem{})
			if err := m.Sub[len(m.Sub)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleListPointerSubElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleListPointerSubElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleListPointerSubElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Foo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Foo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleListSubElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleListSubElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleListSubElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Foo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Foo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleMapElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleMapElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleMapElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sub", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sub == nil {
				m.Sub = make(map[string]SampleMapSubElem)
			}
			var mapkey string
			mapvalue := &SampleMapSubElem{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthGenerated
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthGenerated
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &SampleMapSubElem{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Sub[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleMapPointerElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleMapPointerElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleMapPointerElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleMapPointerSubElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleMapPointerSubElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleMapPointerSubElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Foo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Foo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleMapSubElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleMapSubElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleMapSubElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Foo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Foo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SamplePointerElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SamplePointerElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SamplePointerElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sub", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sub == nil {
				m.Sub = &SamplePointerSubElem{}
			}
			if err := m.Sub.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SamplePointerSubElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SamplePointerSubElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SamplePointerSubElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Foo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Foo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleSubElem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleSubElem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleSubElem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Foo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Foo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGenerated(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGenerated = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/apis/simple/v1/generated.proto", fileDescriptorGenerated)
}

var fileDescriptorGenerated = []byte{
	// 1113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x96, 0xcf, 0x6f, 0x23, 0x35,
	0x14, 0xc7, 0xeb, 0xa4, 0xed, 0x36, 0x4e, 0x53, 0x35, 0xa6, 0xbb, 0x8c, 0x22, 0x91, 0x56, 0x39,
	0xf5, 0xd2, 0x09, 0x2d, 0x05, 0xa5, 0x70, 0x61, 0x93, 0xdd, 0x95, 0x90, 0xa8, 0x76, 0x99, 0x70,
	0x5a, 0x01, 0xa9, 0x33, 0x71, 0x13, 0x6f, 0x66, 0x32, 0xb3, 0x63, 0x4f, 0x44, 0x4e, 0xbb, 0x02,
	0xf1, 0x43, 0x08, 0x24, 0xc4, 0x61, 0x85, 0x84, 0x04, 0xfc, 0x07, 0x5c, 0xf9, 0x13, 0x7a, 0xdc,
	0x1b, 0x7b, 0x0a, 0x34, 0x5c, 0xf9, 0x07, 0xd8, 0x03, 0x42, 0xf6, 0x78, 0x26, 0x33, 0x4d, 0xaa,
	0x76, 0xa5, 0x9d, 0xde, 0xec, 0x67, 0x3f, 0x7f, 0x3f, 0x7e, 0x7e, 0xf6, 0x33, 0xc4, 0x5d, 0xca,
	0x7b, 0x7e, 0x5b, 0x37, 0x1d, 0xbb, 0x3a, 0xf2, 0xc9, 0xc1, 0xc1, 0xfe, 0x7e, 0xad, 0xb6, 0x57,
	0xc5, 0x2e, 0x65, 0xc4, 0x1b, 0x12, 0x6f, 0xa7, 0xed, 0x53, 0xab, 0x43, 0xbc, 0x1d, 0x6c, 0xb9,
	0x3d, 0xbc, 0xe3, 0x7a, 0x0e, 0x77, 0xda, 0xfe, 0xf1, 0x0e, 0xf9, 0x14, 0xdb, 0xae, 0x45, 0xaa,
	0x6e, 0xbf, 0x2b, 0x27, 0x57, 0x19, 0x95, 0xfd, 0xe1, 0x6e, 0xb5, 0x4b, 0x06, 0xc4, 0xc3, 0x9c,
	0x74, 0x74, 0x39, 0x1b, 0x7d, 0x30, 0x95, 0xd0, 0xa7, 0x12, 0x7a, 0x24, 0xd1, 0x52, 0x12, 0x2d,
	0x29, 0xd1, 0x0a, 0x25, 0x5a, 0x4a, 0x42, 0x77, 0xfb, 0x5d, 0x39, 0x59, 0x0f, 0x24, 0xf4, 0xe1,
	0x6e, 0x69, 0x27, 0x46, 0xdd, 0x75, 0xba, 0x4e, 0x35, 0x74, 0x92, 0x3d, 0xd9, 0x91, 0xad, 0x80,
	0xa0, 0xb4, 0xdf, 0xaf, 0x31, 0x9d, 0x3a, 0x02, 0xd4, 0xc6, 0x66, 0x8f, 0x0e, 0x88, 0x37, 0x9a,
	0x92, 0xdb, 0x84, 0xe3, 0x39, 0xdc, 0xa5, 0xea, 0x79, 0x5e, 0x9e, 0x3f, 0xe0, 0xd4, 0x26, 0x33,
	0x0e, 0x6f, 0x5d, 0xe4, 0xc0, 0xcc, 0x1e, 0xb1, 0xf1, 0x8c, 0xdf, 0xbb, 0x8c, 0x76, 0x99, 0x3e,
	0x75, 0x9e, 0x17, 0x79, 0xb9, 0x8e, 0xb2, 0xb0, 0xb3, 0x2b, 0x54, 0xfe, 0xcd, 0xc0, 0x6b, 0xb7,
	0x08, 0x71, 0xef, 0x0e, 0x08, 0x3a, 0x82, 0x2b, 0x62, 0x47, 0x1d, 0xcc, 0xb1, 0x06, 0xb6, 0xc0,
	0x76, 0x7e, 0xef, 0x75, 0xb5, 0xb6, 0x1e, 0x07, 0x9b, 0x86, 0x55, 0xcc, 0xd6, 0x87, 0xbb, 0xfa,
	0xdd, 0xf6, 0x03, 0x62, 0xf2, 0x43, 0xc2, 0x71, 0x1d, 0x9d, 0x8c, 0x37, 0x17, 0x26, 0xe3, 0x4d,
	0x38, 0xb5, 0x19, 0xd1, 0xaa, 0xe8, 0x31, 0x80, 0x8b, 0xcc, 0x25, 0xa6, 0x96, 0x91, 0xcb, 0x7f,
	0xa2, 0xbf, 0xf4, 0x03, 0xd6, 0xd5, 0x66, 0x9a, 0x2e, 0x31, 0xeb, 0xab, 0x0a, 0x66, 0x51, 0xf4,
	0x0c, 0xa9, 0x8c, 0xbe, 0x06, 0x70, 0x99, 0x71, 0xcc, 0x7d, 0xa6, 0x65, 0x25, 0xc4, 0x51, 0x8a,
	0x10, 0x52, 0xa7, 0xbe, 0xa6, 0x30, 0x96, 0x83, 0xbe, 0xa1, 0xf4, 0x2b, 0xff, 0x00, 0x98, 0x57,
	0x33, 0xdf, 0xa7, 0x8c, 0xa3, 0x8f, 0x66, 0xe2, 0xaf, 0x5f, 0x2e, 0xfe, 0xc2, 0x5b, 0x46, 0x7f,
	0x5d, 0x29, 0xad, 0x84, 0x96, 0x58, 0xec, 0x1f, 0xc1, 0x25, 0xca, 0x89, 0xcd, 0xb4, 0xcc, 0x56,
	0x76, 0x3b, 0xbf, 0x77, 0x3f, 0xbd, 0x6d, 0xd7, 0x0b, 0x0a, 0x63, 0xe9, 0x3d, 0x21, 0x68, 0x04,
	0xba, 0x95, 0x3f, 0xd6, 0xa2, 0xed, 0x8a, 0xf3, 0x40, 0x07, 0xb0, 0x70, 0x4c, 0x59, 0xaf, 0xe5,
	0x91, 0x87, 0x3e, 0xf5, 0x48, 0x47, 0xee, 0x39, 0x5b, 0xdf, 0x50, 0xce, 0xab, 0x77, 0x28, 0xeb,
	0x19, 0x6a, 0xcc, 0x58, 0x3d, 0x8e, 0xf5, 0xd0, 0x17, 0xe2, 0x10, 0x25, 0x86, 0xca, 0xa4, 0x8f,
	0x53, 0xd8, 0x4d, 0x53, 0x8e, 0xdc, 0xb6, 0x88, 0x1d, 0x3b, 0x41, 0x69, 0x33, 0x94, 0x38, 0xfa,
	0x19, 0xc0, 0xb5, 0xa0, 0xd9, 0x72, 0x1d, 0x3a, 0xe0, 0xc4, 0x53, 0x49, 0xd5, 0x49, 0x8d, 0xe7,
	0x5e, 0xa0, 0x23, 0xb1, 0x8a, 0x93, 0xf1, 0x66, 0x21, 0x61, 0x36, 0x0a, 0x2c, 0xde, 0x45, 0x4f,
	0x00, 0xcc, 0x2b, 0x40, 0x8b, 0x32, 0xae, 0x2d, 0xca, 0xb3, 0xc7, 0xa9, 0xd1, 0x89, 0xbc, 0x93,
	0x68, 0xd1, 0x3b, 0x30, 0xb5, 0x1b, 0x90, 0x45, 0x6d, 0xf4, 0x1b, 0x80, 0xaf, 0x24, 0x23, 0x17,
	0x00, 0x2e, 0x49, 0xc0, 0x5e, 0xaa, 0x80, 0xf1, 0x10, 0x5e, 0x9f, 0x8c, 0x37, 0x8b, 0x89, 0x10,
	0x4a, 0xd4, 0x22, 0x3b, 0x6b, 0x42, 0xbf, 0x00, 0xa8, 0x36, 0xd0, 0xb2, 0xb1, 0xab, 0x2d, 0x4b,
	0x50, 0x3b, 0xdd, 0x17, 0x4c, 0x41, 0x1f, 0x62, 0xf7, 0xf6, 0x80, 0x7b, 0xa3, 0x7a, 0x51, 0x45,
	0x35, 0x17, 0xd9, 0x8d, 0x1c, 0x0b, 0x9b, 0xe8, 0x01, 0xbc, 0x11, 0x86, 0xd4, 0xa3, 0x36, 0xe5,
	0x74, 0x48, 0x5a, 0xd8, 0xa2, 0x98, 0x69, 0x2b, 0xf2, 0x66, 0xed, 0x2b, 0xef, 0x0d, 0xb5, 0xdf,
	0x70, 0xd2, 0x4d, 0x31, 0xe7, 0xf9, 0x39, 0x76, 0x63, 0x83, 0xcd, 0xb1, 0xa2, 0xaf, 0x00, 0x5c,
	0x32, 0x9d, 0x01, 0xe3, 0x5a, 0x6e, 0x0b, 0x6c, 0xe7, 0xea, 0x0f, 0xc3, 0x2b, 0xdf, 0x10, 0xc6,
	0xe7, 0xe3, 0xcd, 0xa3, 0x97, 0xfc, 0x3d, 0x30, 0x1d, 0xdb, 0x76, 0x06, 0x7a, 0xc3, 0x67, 0xdc,
	0xb1, 0x3f, 0x1c, 0xb9, 0xc4, 0x08, 0xf4, 0xd1, 0xb7, 0x00, 0xae, 0xc8, 0xd6, 0x3d, 0xee, 0x69,
	0x50, 0xc2, 0xb8, 0xe2, 0x09, 0x6c, 0x28, 0xdb, 0x95, 0xb0, 0x44, 0x04, 0xe8, 0x07, 0x00, 0xa1,
	0xec, 0x34, 0x2d, 0x6a, 0x12, 0x2d, 0xbf, 0x95, 0xdd, 0xce, 0xd5, 0x3d, 0x71, 0x13, 0x1a, 0x91,
	0xf5, 0x4a, 0x90, 0x62, 0x14, 0xe8, 0xbf, 0x30, 0x46, 0x87, 0xd8, 0xd5, 0x56, 0x65, 0xe6, 0x5a,
	0x29, 0x67, 0x6e, 0x43, 0xc9, 0x05, 0x89, 0xcb, 0xc3, 0xc2, 0x14, 0x9a, 0xbf, 0xf9, 0xf3, 0xca,
	0x4e, 0xe5, 0x10, 0xbb, 0x25, 0xf1, 0x50, 0x27, 0xef, 0x12, 0x5a, 0x87, 0xd9, 0x3e, 0x19, 0xc9,
	0xa2, 0x93, 0x33, 0x44, 0x13, 0x0d, 0xe1, 0xd2, 0x10, 0x5b, 0x7e, 0x58, 0x53, 0x8e, 0x52, 0x7b,
	0x84, 0x04, 0x83, 0x45, 0x6c, 0x23, 0x90, 0x7b, 0x3b, 0x53, 0x03, 0xa5, 0x77, 0x60, 0x21, 0x11,
	0xb1, 0x39, 0x78, 0x1b, 0x71, 0xbc, 0x5c, 0xcc, 0xb9, 0x72, 0x0b, 0x16, 0x12, 0x3f, 0x0e, 0xf4,
	0x06, 0xcc, 0x63, 0x93, 0xfb, 0xd8, 0x6a, 0x89, 0xb2, 0xa9, 0x0a, 0x6b, 0xf4, 0x24, 0xdf, 0x94,
	0x43, 0xb2, 0xbc, 0x42, 0x1c, 0xb5, 0x2b, 0xdf, 0x01, 0x08, 0xa7, 0x35, 0x0f, 0x3d, 0x82, 0x59,
	0xe6, 0xb7, 0xd5, 0x47, 0x24, 0xbd, 0x58, 0x34, 0xfd, 0xb6, 0x7c, 0x88, 0xf3, 0x8a, 0x2e, 0xdb,
	0xf4, 0xdb, 0x86, 0x50, 0xae, 0x3c, 0x89, 0xce, 0x2c, 0xac, 0x2a, 0xe8, 0x73, 0x10, 0x42, 0x65,
	0x53, 0x2d, 0xb2, 0x42, 0xf0, 0x7c, 0xb0, 0x5f, 0x01, 0xbc, 0x3e, 0xb7, 0x9a, 0xa0, 0x2f, 0x13,
	0x7c, 0xfd, 0xab, 0xa8, 0x62, 0x21, 0xe6, 0xb5, 0x04, 0xe2, 0x01, 0xd4, 0xce, 0x9b, 0x89, 0x5e,
	0x83, 0xd9, 0x63, 0xc7, 0x09, 0x32, 0x6b, 0xba, 0xbb, 0x3b, 0x8e, 0x63, 0x08, 0x7b, 0x65, 0x0f,
	0x16, 0x67, 0x82, 0x70, 0x91, 0xcf, 0xef, 0x19, 0x58, 0x48, 0xa4, 0xb6, 0xf8, 0x66, 0xc7, 0x22,
	0x41, 0xd3, 0xbe, 0x4a, 0xba, 0x00, 0x95, 0x2f, 0xcd, 0xcc, 0x71, 0x95, 0x7e, 0x02, 0x70, 0x25,
	0x1c, 0x9e, 0x73, 0xad, 0x46, 0xc9, 0x5b, 0x6f, 0xa6, 0x89, 0xaa, 0xc2, 0x19, 0xbf, 0xbb, 0x37,
	0xe0, 0x46, 0x34, 0x1c, 0x4b, 0xa5, 0x4a, 0x0d, 0xbe, 0x7a, 0xd6, 0x7e, 0xc9, 0xc3, 0xd8, 0x85,
	0xeb, 0x67, 0x05, 0x2f, 0x72, 0xf9, 0x11, 0xc0, 0xe2, 0xcc, 0xf7, 0x12, 0x7d, 0x06, 0xe2, 0x4f,
	0x40, 0x37, 0xed, 0x2f, 0xed, 0xfc, 0x4c, 0x7e, 0x33, 0x8c, 0xcf, 0x8b, 0x05, 0x41, 0x0f, 0x13,
	0xf2, 0x72, 0xf3, 0xeb, 0xdb, 0x27, 0xa7, 0xe5, 0x85, 0xa7, 0xa7, 0xe5, 0x85, 0x67, 0xa7, 0xe5,
	0x85, 0xc7, 0x93, 0x32, 0x38, 0x99, 0x94, 0xc1, 0xd3, 0x49, 0x19, 0x3c, 0x9b, 0x94, 0xc1, 0x5f,
	0x93, 0x32, 0xf8, 0xfe, 0xef, 0xf2, 0xc2, 0xfd, 0xcc, 0x70, 0xf7, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa4, 0x75, 0x55, 0x0a, 0xf8, 0x10, 0x00, 0x00,
}
