// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	simple "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/apis/simple"
	common "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/apis/simple/common"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DeepOne)(nil), (*simple.DeepOne)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DeepOne_To_simple_DeepOne(a.(*DeepOne), b.(*simple.DeepOne), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.DeepOne)(nil), (*DeepOne)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_DeepOne_To_v1_DeepOne(a.(*simple.DeepOne), b.(*DeepOne), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeepOneList)(nil), (*simple.DeepOneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DeepOneList_To_simple_DeepOneList(a.(*DeepOneList), b.(*simple.DeepOneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.DeepOneList)(nil), (*DeepOneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_DeepOneList_To_v1_DeepOneList(a.(*simple.DeepOneList), b.(*DeepOneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeepOneSpec)(nil), (*simple.DeepOneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DeepOneSpec_To_simple_DeepOneSpec(a.(*DeepOneSpec), b.(*simple.DeepOneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.DeepOneSpec)(nil), (*DeepOneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_DeepOneSpec_To_v1_DeepOneSpec(a.(*simple.DeepOneSpec), b.(*DeepOneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeepOneStatus)(nil), (*simple.DeepOneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DeepOneStatus_To_simple_DeepOneStatus(a.(*DeepOneStatus), b.(*simple.DeepOneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.DeepOneStatus)(nil), (*DeepOneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_DeepOneStatus_To_v1_DeepOneStatus(a.(*simple.DeepOneStatus), b.(*DeepOneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleElem)(nil), (*simple.SampleElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleElem_To_simple_SampleElem(a.(*SampleElem), b.(*simple.SampleElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleElem)(nil), (*SampleElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleElem_To_v1_SampleElem(a.(*simple.SampleElem), b.(*SampleElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleListElem)(nil), (*simple.SampleListElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleListElem_To_simple_SampleListElem(a.(*SampleListElem), b.(*simple.SampleListElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleListElem)(nil), (*SampleListElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleListElem_To_v1_SampleListElem(a.(*simple.SampleListElem), b.(*SampleListElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleListPointerElem)(nil), (*simple.SampleListPointerElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleListPointerElem_To_simple_SampleListPointerElem(a.(*SampleListPointerElem), b.(*simple.SampleListPointerElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleListPointerElem)(nil), (*SampleListPointerElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleListPointerElem_To_v1_SampleListPointerElem(a.(*simple.SampleListPointerElem), b.(*SampleListPointerElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleListPointerSubElem)(nil), (*simple.SampleListPointerSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleListPointerSubElem_To_simple_SampleListPointerSubElem(a.(*SampleListPointerSubElem), b.(*simple.SampleListPointerSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleListPointerSubElem)(nil), (*SampleListPointerSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleListPointerSubElem_To_v1_SampleListPointerSubElem(a.(*simple.SampleListPointerSubElem), b.(*SampleListPointerSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleListSubElem)(nil), (*simple.SampleListSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleListSubElem_To_simple_SampleListSubElem(a.(*SampleListSubElem), b.(*simple.SampleListSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleListSubElem)(nil), (*SampleListSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleListSubElem_To_v1_SampleListSubElem(a.(*simple.SampleListSubElem), b.(*SampleListSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleMapElem)(nil), (*simple.SampleMapElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleMapElem_To_simple_SampleMapElem(a.(*SampleMapElem), b.(*simple.SampleMapElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleMapElem)(nil), (*SampleMapElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleMapElem_To_v1_SampleMapElem(a.(*simple.SampleMapElem), b.(*SampleMapElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleMapSubElem)(nil), (*simple.SampleMapSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleMapSubElem_To_simple_SampleMapSubElem(a.(*SampleMapSubElem), b.(*simple.SampleMapSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleMapSubElem)(nil), (*SampleMapSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleMapSubElem_To_v1_SampleMapSubElem(a.(*simple.SampleMapSubElem), b.(*SampleMapSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SamplePointerElem)(nil), (*simple.SamplePointerElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SamplePointerElem_To_simple_SamplePointerElem(a.(*SamplePointerElem), b.(*simple.SamplePointerElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SamplePointerElem)(nil), (*SamplePointerElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SamplePointerElem_To_v1_SamplePointerElem(a.(*simple.SamplePointerElem), b.(*SamplePointerElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SamplePointerSubElem)(nil), (*simple.SamplePointerSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SamplePointerSubElem_To_simple_SamplePointerSubElem(a.(*SamplePointerSubElem), b.(*simple.SamplePointerSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SamplePointerSubElem)(nil), (*SamplePointerSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SamplePointerSubElem_To_v1_SamplePointerSubElem(a.(*simple.SamplePointerSubElem), b.(*SamplePointerSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SampleSubElem)(nil), (*simple.SampleSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SampleSubElem_To_simple_SampleSubElem(a.(*SampleSubElem), b.(*simple.SampleSubElem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*simple.SampleSubElem)(nil), (*SampleSubElem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_simple_SampleSubElem_To_v1_SampleSubElem(a.(*simple.SampleSubElem), b.(*SampleSubElem), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_DeepOne_To_simple_DeepOne(in *DeepOne, out *simple.DeepOne, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_DeepOneSpec_To_simple_DeepOneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_DeepOneStatus_To_simple_DeepOneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_DeepOne_To_simple_DeepOne is an autogenerated conversion function.
func Convert_v1_DeepOne_To_simple_DeepOne(in *DeepOne, out *simple.DeepOne, s conversion.Scope) error {
	return autoConvert_v1_DeepOne_To_simple_DeepOne(in, out, s)
}

func autoConvert_simple_DeepOne_To_v1_DeepOne(in *simple.DeepOne, out *DeepOne, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_simple_DeepOneSpec_To_v1_DeepOneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_simple_DeepOneStatus_To_v1_DeepOneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_simple_DeepOne_To_v1_DeepOne is an autogenerated conversion function.
func Convert_simple_DeepOne_To_v1_DeepOne(in *simple.DeepOne, out *DeepOne, s conversion.Scope) error {
	return autoConvert_simple_DeepOne_To_v1_DeepOne(in, out, s)
}

func autoConvert_v1_DeepOneList_To_simple_DeepOneList(in *DeepOneList, out *simple.DeepOneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]simple.DeepOne)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_DeepOneList_To_simple_DeepOneList is an autogenerated conversion function.
func Convert_v1_DeepOneList_To_simple_DeepOneList(in *DeepOneList, out *simple.DeepOneList, s conversion.Scope) error {
	return autoConvert_v1_DeepOneList_To_simple_DeepOneList(in, out, s)
}

func autoConvert_simple_DeepOneList_To_v1_DeepOneList(in *simple.DeepOneList, out *DeepOneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DeepOne)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_simple_DeepOneList_To_v1_DeepOneList is an autogenerated conversion function.
func Convert_simple_DeepOneList_To_v1_DeepOneList(in *simple.DeepOneList, out *DeepOneList, s conversion.Scope) error {
	return autoConvert_simple_DeepOneList_To_v1_DeepOneList(in, out, s)
}

func autoConvert_v1_DeepOneSpec_To_simple_DeepOneSpec(in *DeepOneSpec, out *simple.DeepOneSpec, s conversion.Scope) error {
	out.FishRequired = in.FishRequired
	if err := Convert_v1_SampleElem_To_simple_SampleElem(&in.Sample, &out.Sample, s); err != nil {
		return err
	}
	out.SamplePointer = (*simple.SamplePointerElem)(unsafe.Pointer(in.SamplePointer))
	out.SampleList = *(*[]simple.SampleListElem)(unsafe.Pointer(&in.SampleList))
	out.SamplePointerList = *(*[]*simple.SampleListPointerElem)(unsafe.Pointer(&in.SamplePointerList))
	out.SampleMap = *(*map[string]simple.SampleMapElem)(unsafe.Pointer(&in.SampleMap))
	out.SamplePrimitiveAlias = simple.SamplePrimitiveAlias(in.SamplePrimitiveAlias)
	out.Const = common.CustomType(in.Const)
	out.ConstPtr = (*common.CustomType)(unsafe.Pointer(in.ConstPtr))
	out.ConstSlice = *(*[]common.CustomType)(unsafe.Pointer(&in.ConstSlice))
	out.ConstMap = *(*map[string]common.CustomType)(unsafe.Pointer(&in.ConstMap))
	return nil
}

// Convert_v1_DeepOneSpec_To_simple_DeepOneSpec is an autogenerated conversion function.
func Convert_v1_DeepOneSpec_To_simple_DeepOneSpec(in *DeepOneSpec, out *simple.DeepOneSpec, s conversion.Scope) error {
	return autoConvert_v1_DeepOneSpec_To_simple_DeepOneSpec(in, out, s)
}

func autoConvert_simple_DeepOneSpec_To_v1_DeepOneSpec(in *simple.DeepOneSpec, out *DeepOneSpec, s conversion.Scope) error {
	out.FishRequired = in.FishRequired
	if err := Convert_simple_SampleElem_To_v1_SampleElem(&in.Sample, &out.Sample, s); err != nil {
		return err
	}
	out.SamplePointer = (*SamplePointerElem)(unsafe.Pointer(in.SamplePointer))
	out.SampleList = *(*[]SampleListElem)(unsafe.Pointer(&in.SampleList))
	out.SamplePointerList = *(*[]*SampleListPointerElem)(unsafe.Pointer(&in.SamplePointerList))
	out.SampleMap = *(*map[string]SampleMapElem)(unsafe.Pointer(&in.SampleMap))
	out.SamplePrimitiveAlias = SamplePrimitiveAlias(in.SamplePrimitiveAlias)
	out.Const = common.CustomType(in.Const)
	out.ConstPtr = (*common.CustomType)(unsafe.Pointer(in.ConstPtr))
	out.ConstSlice = *(*[]common.CustomType)(unsafe.Pointer(&in.ConstSlice))
	out.ConstMap = *(*map[string]common.CustomType)(unsafe.Pointer(&in.ConstMap))
	return nil
}

// Convert_simple_DeepOneSpec_To_v1_DeepOneSpec is an autogenerated conversion function.
func Convert_simple_DeepOneSpec_To_v1_DeepOneSpec(in *simple.DeepOneSpec, out *DeepOneSpec, s conversion.Scope) error {
	return autoConvert_simple_DeepOneSpec_To_v1_DeepOneSpec(in, out, s)
}

func autoConvert_v1_DeepOneStatus_To_simple_DeepOneStatus(in *DeepOneStatus, out *simple.DeepOneStatus, s conversion.Scope) error {
	out.ActualFish = in.ActualFish
	return nil
}

// Convert_v1_DeepOneStatus_To_simple_DeepOneStatus is an autogenerated conversion function.
func Convert_v1_DeepOneStatus_To_simple_DeepOneStatus(in *DeepOneStatus, out *simple.DeepOneStatus, s conversion.Scope) error {
	return autoConvert_v1_DeepOneStatus_To_simple_DeepOneStatus(in, out, s)
}

func autoConvert_simple_DeepOneStatus_To_v1_DeepOneStatus(in *simple.DeepOneStatus, out *DeepOneStatus, s conversion.Scope) error {
	out.ActualFish = in.ActualFish
	return nil
}

// Convert_simple_DeepOneStatus_To_v1_DeepOneStatus is an autogenerated conversion function.
func Convert_simple_DeepOneStatus_To_v1_DeepOneStatus(in *simple.DeepOneStatus, out *DeepOneStatus, s conversion.Scope) error {
	return autoConvert_simple_DeepOneStatus_To_v1_DeepOneStatus(in, out, s)
}

func autoConvert_v1_SampleElem_To_simple_SampleElem(in *SampleElem, out *simple.SampleElem, s conversion.Scope) error {
	if err := Convert_v1_SampleSubElem_To_simple_SampleSubElem(&in.Sub, &out.Sub, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_SampleElem_To_simple_SampleElem is an autogenerated conversion function.
func Convert_v1_SampleElem_To_simple_SampleElem(in *SampleElem, out *simple.SampleElem, s conversion.Scope) error {
	return autoConvert_v1_SampleElem_To_simple_SampleElem(in, out, s)
}

func autoConvert_simple_SampleElem_To_v1_SampleElem(in *simple.SampleElem, out *SampleElem, s conversion.Scope) error {
	if err := Convert_simple_SampleSubElem_To_v1_SampleSubElem(&in.Sub, &out.Sub, s); err != nil {
		return err
	}
	return nil
}

// Convert_simple_SampleElem_To_v1_SampleElem is an autogenerated conversion function.
func Convert_simple_SampleElem_To_v1_SampleElem(in *simple.SampleElem, out *SampleElem, s conversion.Scope) error {
	return autoConvert_simple_SampleElem_To_v1_SampleElem(in, out, s)
}

func autoConvert_v1_SampleListElem_To_simple_SampleListElem(in *SampleListElem, out *simple.SampleListElem, s conversion.Scope) error {
	out.Sub = *(*[]simple.SampleListSubElem)(unsafe.Pointer(&in.Sub))
	return nil
}

// Convert_v1_SampleListElem_To_simple_SampleListElem is an autogenerated conversion function.
func Convert_v1_SampleListElem_To_simple_SampleListElem(in *SampleListElem, out *simple.SampleListElem, s conversion.Scope) error {
	return autoConvert_v1_SampleListElem_To_simple_SampleListElem(in, out, s)
}

func autoConvert_simple_SampleListElem_To_v1_SampleListElem(in *simple.SampleListElem, out *SampleListElem, s conversion.Scope) error {
	out.Sub = *(*[]SampleListSubElem)(unsafe.Pointer(&in.Sub))
	return nil
}

// Convert_simple_SampleListElem_To_v1_SampleListElem is an autogenerated conversion function.
func Convert_simple_SampleListElem_To_v1_SampleListElem(in *simple.SampleListElem, out *SampleListElem, s conversion.Scope) error {
	return autoConvert_simple_SampleListElem_To_v1_SampleListElem(in, out, s)
}

func autoConvert_v1_SampleListPointerElem_To_simple_SampleListPointerElem(in *SampleListPointerElem, out *simple.SampleListPointerElem, s conversion.Scope) error {
	out.Sub = *(*[]*simple.SampleListPointerSubElem)(unsafe.Pointer(&in.Sub))
	return nil
}

// Convert_v1_SampleListPointerElem_To_simple_SampleListPointerElem is an autogenerated conversion function.
func Convert_v1_SampleListPointerElem_To_simple_SampleListPointerElem(in *SampleListPointerElem, out *simple.SampleListPointerElem, s conversion.Scope) error {
	return autoConvert_v1_SampleListPointerElem_To_simple_SampleListPointerElem(in, out, s)
}

func autoConvert_simple_SampleListPointerElem_To_v1_SampleListPointerElem(in *simple.SampleListPointerElem, out *SampleListPointerElem, s conversion.Scope) error {
	out.Sub = *(*[]*SampleListPointerSubElem)(unsafe.Pointer(&in.Sub))
	return nil
}

// Convert_simple_SampleListPointerElem_To_v1_SampleListPointerElem is an autogenerated conversion function.
func Convert_simple_SampleListPointerElem_To_v1_SampleListPointerElem(in *simple.SampleListPointerElem, out *SampleListPointerElem, s conversion.Scope) error {
	return autoConvert_simple_SampleListPointerElem_To_v1_SampleListPointerElem(in, out, s)
}

func autoConvert_v1_SampleListPointerSubElem_To_simple_SampleListPointerSubElem(in *SampleListPointerSubElem, out *simple.SampleListPointerSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_v1_SampleListPointerSubElem_To_simple_SampleListPointerSubElem is an autogenerated conversion function.
func Convert_v1_SampleListPointerSubElem_To_simple_SampleListPointerSubElem(in *SampleListPointerSubElem, out *simple.SampleListPointerSubElem, s conversion.Scope) error {
	return autoConvert_v1_SampleListPointerSubElem_To_simple_SampleListPointerSubElem(in, out, s)
}

func autoConvert_simple_SampleListPointerSubElem_To_v1_SampleListPointerSubElem(in *simple.SampleListPointerSubElem, out *SampleListPointerSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_simple_SampleListPointerSubElem_To_v1_SampleListPointerSubElem is an autogenerated conversion function.
func Convert_simple_SampleListPointerSubElem_To_v1_SampleListPointerSubElem(in *simple.SampleListPointerSubElem, out *SampleListPointerSubElem, s conversion.Scope) error {
	return autoConvert_simple_SampleListPointerSubElem_To_v1_SampleListPointerSubElem(in, out, s)
}

func autoConvert_v1_SampleListSubElem_To_simple_SampleListSubElem(in *SampleListSubElem, out *simple.SampleListSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_v1_SampleListSubElem_To_simple_SampleListSubElem is an autogenerated conversion function.
func Convert_v1_SampleListSubElem_To_simple_SampleListSubElem(in *SampleListSubElem, out *simple.SampleListSubElem, s conversion.Scope) error {
	return autoConvert_v1_SampleListSubElem_To_simple_SampleListSubElem(in, out, s)
}

func autoConvert_simple_SampleListSubElem_To_v1_SampleListSubElem(in *simple.SampleListSubElem, out *SampleListSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_simple_SampleListSubElem_To_v1_SampleListSubElem is an autogenerated conversion function.
func Convert_simple_SampleListSubElem_To_v1_SampleListSubElem(in *simple.SampleListSubElem, out *SampleListSubElem, s conversion.Scope) error {
	return autoConvert_simple_SampleListSubElem_To_v1_SampleListSubElem(in, out, s)
}

func autoConvert_v1_SampleMapElem_To_simple_SampleMapElem(in *SampleMapElem, out *simple.SampleMapElem, s conversion.Scope) error {
	out.Sub = *(*map[string]simple.SampleMapSubElem)(unsafe.Pointer(&in.Sub))
	return nil
}

// Convert_v1_SampleMapElem_To_simple_SampleMapElem is an autogenerated conversion function.
func Convert_v1_SampleMapElem_To_simple_SampleMapElem(in *SampleMapElem, out *simple.SampleMapElem, s conversion.Scope) error {
	return autoConvert_v1_SampleMapElem_To_simple_SampleMapElem(in, out, s)
}

func autoConvert_simple_SampleMapElem_To_v1_SampleMapElem(in *simple.SampleMapElem, out *SampleMapElem, s conversion.Scope) error {
	out.Sub = *(*map[string]SampleMapSubElem)(unsafe.Pointer(&in.Sub))
	return nil
}

// Convert_simple_SampleMapElem_To_v1_SampleMapElem is an autogenerated conversion function.
func Convert_simple_SampleMapElem_To_v1_SampleMapElem(in *simple.SampleMapElem, out *SampleMapElem, s conversion.Scope) error {
	return autoConvert_simple_SampleMapElem_To_v1_SampleMapElem(in, out, s)
}

func autoConvert_v1_SampleMapSubElem_To_simple_SampleMapSubElem(in *SampleMapSubElem, out *simple.SampleMapSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_v1_SampleMapSubElem_To_simple_SampleMapSubElem is an autogenerated conversion function.
func Convert_v1_SampleMapSubElem_To_simple_SampleMapSubElem(in *SampleMapSubElem, out *simple.SampleMapSubElem, s conversion.Scope) error {
	return autoConvert_v1_SampleMapSubElem_To_simple_SampleMapSubElem(in, out, s)
}

func autoConvert_simple_SampleMapSubElem_To_v1_SampleMapSubElem(in *simple.SampleMapSubElem, out *SampleMapSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_simple_SampleMapSubElem_To_v1_SampleMapSubElem is an autogenerated conversion function.
func Convert_simple_SampleMapSubElem_To_v1_SampleMapSubElem(in *simple.SampleMapSubElem, out *SampleMapSubElem, s conversion.Scope) error {
	return autoConvert_simple_SampleMapSubElem_To_v1_SampleMapSubElem(in, out, s)
}

func autoConvert_v1_SamplePointerElem_To_simple_SamplePointerElem(in *SamplePointerElem, out *simple.SamplePointerElem, s conversion.Scope) error {
	out.Sub = (*simple.SamplePointerSubElem)(unsafe.Pointer(in.Sub))
	return nil
}

// Convert_v1_SamplePointerElem_To_simple_SamplePointerElem is an autogenerated conversion function.
func Convert_v1_SamplePointerElem_To_simple_SamplePointerElem(in *SamplePointerElem, out *simple.SamplePointerElem, s conversion.Scope) error {
	return autoConvert_v1_SamplePointerElem_To_simple_SamplePointerElem(in, out, s)
}

func autoConvert_simple_SamplePointerElem_To_v1_SamplePointerElem(in *simple.SamplePointerElem, out *SamplePointerElem, s conversion.Scope) error {
	out.Sub = (*SamplePointerSubElem)(unsafe.Pointer(in.Sub))
	return nil
}

// Convert_simple_SamplePointerElem_To_v1_SamplePointerElem is an autogenerated conversion function.
func Convert_simple_SamplePointerElem_To_v1_SamplePointerElem(in *simple.SamplePointerElem, out *SamplePointerElem, s conversion.Scope) error {
	return autoConvert_simple_SamplePointerElem_To_v1_SamplePointerElem(in, out, s)
}

func autoConvert_v1_SamplePointerSubElem_To_simple_SamplePointerSubElem(in *SamplePointerSubElem, out *simple.SamplePointerSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_v1_SamplePointerSubElem_To_simple_SamplePointerSubElem is an autogenerated conversion function.
func Convert_v1_SamplePointerSubElem_To_simple_SamplePointerSubElem(in *SamplePointerSubElem, out *simple.SamplePointerSubElem, s conversion.Scope) error {
	return autoConvert_v1_SamplePointerSubElem_To_simple_SamplePointerSubElem(in, out, s)
}

func autoConvert_simple_SamplePointerSubElem_To_v1_SamplePointerSubElem(in *simple.SamplePointerSubElem, out *SamplePointerSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_simple_SamplePointerSubElem_To_v1_SamplePointerSubElem is an autogenerated conversion function.
func Convert_simple_SamplePointerSubElem_To_v1_SamplePointerSubElem(in *simple.SamplePointerSubElem, out *SamplePointerSubElem, s conversion.Scope) error {
	return autoConvert_simple_SamplePointerSubElem_To_v1_SamplePointerSubElem(in, out, s)
}

func autoConvert_v1_SampleSubElem_To_simple_SampleSubElem(in *SampleSubElem, out *simple.SampleSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_v1_SampleSubElem_To_simple_SampleSubElem is an autogenerated conversion function.
func Convert_v1_SampleSubElem_To_simple_SampleSubElem(in *SampleSubElem, out *simple.SampleSubElem, s conversion.Scope) error {
	return autoConvert_v1_SampleSubElem_To_simple_SampleSubElem(in, out, s)
}

func autoConvert_simple_SampleSubElem_To_v1_SampleSubElem(in *simple.SampleSubElem, out *SampleSubElem, s conversion.Scope) error {
	out.Foo = in.Foo
	return nil
}

// Convert_simple_SampleSubElem_To_v1_SampleSubElem is an autogenerated conversion function.
func Convert_simple_SampleSubElem_To_v1_SampleSubElem(in *simple.SampleSubElem, out *SampleSubElem, s conversion.Scope) error {
	return autoConvert_simple_SampleSubElem_To_v1_SampleSubElem(in, out, s)
}
