// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/client/clientset_generated/clientset/typed/simple/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSimpleV1 struct {
	*testing.Fake
}

func (c *FakeSimpleV1) DeepOnes(namespace string) v1.DeepOneInterface {
	return &FakeDeepOnes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSimpleV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
