// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	simplev1 "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/apis/simple/v1"
	clientset "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1 "github.com/yue9944882/apiserver-builder-alpha-protobuf-example/pkg/client/listers_generated/simple/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeepOneInformer provides access to a shared informer and lister for
// DeepOnes.
type DeepOneInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DeepOneLister
}

type deepOneInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeepOneInformer constructs a new informer for DeepOne type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeepOneInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeepOneInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeepOneInformer constructs a new informer for DeepOne type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeepOneInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SimpleV1().DeepOnes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SimpleV1().DeepOnes(namespace).Watch(options)
			},
		},
		&simplev1.DeepOne{},
		resyncPeriod,
		indexers,
	)
}

func (f *deepOneInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeepOneInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deepOneInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&simplev1.DeepOne{}, f.defaultInformer)
}

func (f *deepOneInformer) Lister() v1.DeepOneLister {
	return v1.NewDeepOneLister(f.Informer().GetIndexer())
}
